require('base')
require('color')
require('keymap')
require('plugins')
require('plugin-config/nvim-treesitter')
require('plugin-config/mason')
require('plugin-config/mason-lspconfig')
require('plugin-config/nvim-lspconfig')
require('plugin-config/nvim-cmp')
require('plugin-config/nvim-tree')
require('plugin-config/bufferline')
require('plugin-config/telescope')

